on:
  push:
  workflow_dispatch:
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - depandecy-name: "discord.js"
      
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"
    
  - package-ecosystem: "docker"
    directory: ".docker/"
    schedule:
      interval: "daily"
      
  #  - package-ecosystem: "kubernetes"
  #  directory: "/"
  #  schedule:
  #    interval: "daily"
    
  #- package-ecosystem: "python"
  #  directory: "/"
  #  schedule:
  #  interval: "daily"
    
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    
  #  - package-ecosystem: "pip"
  # directory: "/"
  #  schedule:
  #    interval: "daily"
    
  #  - package-ecosystem: "pip-env"
  #  directory: "/"
  #  schedule:
  #    interval: "daily"
    
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
